#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jan 23 12:08:36 2020

@author: alex
"""

import numpy as np
from pyro.dynamic  import integrator


###################################
# Simple integrator
sys      = integrator.SimpleIntegrator()

# Default input signal
sys.ubar = np.array([1]) 

# Phase plane behavior
sys.plot_phase_plane(0,0) # only one state for two axis!

# Initial conditions
sys.x0   = np.array([2]) 

# Simulation
traj = sys.compute_trajectory()

# Plot output
sys.plot_trajectory()
sys.plot_phase_plane_trajectory(0,0)